global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    environment: staging

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "opspilot-api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "api:8000"

  - job_name: "opspilot-staging-http-probe"
    metrics_path: /probe
    params:
      module:
        - http_2xx

    static_configs:
      - targets:
          - http://nginx/health
        labels:
          environment: staging

    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target

      - source_labels:
          - __param_target
        target_label: instance

      - target_label: __address__
        replacement: blackbox:9115
